apps:
- vhost: www.yesodweb.com
  dir: /app/yesodweb.com
  exe: yesodweb
  args:
  - production
- vhost: www.dollarversusshekel.info
  dir: /app
  exe: dollarversusshekel
  args:
  - production
- vhost: www.haskellers.com
  dir: /app/haskellers
  exe: haskellers
  args:
  - production
- vhost: luach.snoyman.com
  dir: /app/luach
  exe: luach
  args:
  - production
- vhost: www.snoyman.com
  dir: /app
  exe: snoymancom
  args:
  - production
- vhost: www.whosawthatcoming.com
  dir: /app/whosawthatcoming
  exe: whosawthatcoming
  args:
  - production

redirects:
- src: yesodweb.com
  dst: www.yesodweb.com
- src: yesodweb.org
  dst: www.yesodweb.com
- src: www.yesodweb.org
  dst: www.yesodweb.com
- src: dollarversusshekel.info
  dst: www.dollarversusshekel.info
- src: haskellers.com
  dst: www.haskellers.com
- src: snoyman.com
  dst: www.snoyman.com
- src: michael.snoyman.com
  dst: www.snoyman.com
- src: whosawthatcoming.com
  dst: www.whosawthatcoming.com
